### ISSUE TITLE
Error when downloading demographic data

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1552]
**Describe the bug**
Received an error (7k8m0glc3) when trying to download a CVS of the demographic data when logged on a CiviForm Admin 

**To Reproduce**
1. Login in as CiviForm Admin
2. Click on 'Programs'
3. Scroll down and click on 'Download Exported Data (CSV)'
4. See error: 7k8m0glc3

**Expected behavior**
Would expect an excel download of data fields

**Screenshots**
Attached
![Download Demographics Error](https://user-images.githubusercontent.com/86082659/124162449-4b930880-da53-11eb-8dc9-62e5d49674d2.JPG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hmhsu** [comment]
Here is the log
![Screen Shot 2021-07-01 at 11 36 02 AM](https://user-images.githubusercontent.com/2597580/124173917-8fd8d580-da60-11eb-8bc4-d6be9f17b155.png)

Or in text
```
  | 2021-07-01T09:57:47.759-07:00 | Caused by: java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: services.question.exceptions.QuestionNotFoundException: Question not found for ID: 84
  | 2021-07-01T09:57:47.759-07:00 | at services.program.ProgramServiceImpl.getProgramDefinition(ProgramServiceImpl.java:64)
  | 2021-07-01T09:57:47.759-07:00 | at services.applicant.ApplicantServiceImpl.getReadOnlyApplicantProgramService(ApplicantServiceImpl.java:113)
  | 2021-07-01T09:57:47.759-07:00 | at services.export.ExporterService.exportCsv(ExporterService.java:91)
  | 2021-07-01T09:57:47.759-07:00 | at services.export.ExporterService.getDemographicsCsv(ExporterService.java:236)
  | 2021-07-01T09:57:47.759-07:00 | at controllers.admin.AdminApplicationController.downloadDemographics(AdminApplicationController.java:91)
```

**Comment by hmhsu** [comment]
This is related to #1290. Question 84 was the problem question in the issue. This is corrupted data we didn't fully clean up. The programming logic should have been fixed.

**Comment by hmhsu** [comment]
The issue is that there are programs which have question 84, but they really should be referring to the new version of the question (id 144).

To confirm, we currently have 2 programs referenced by applications (triggered by demographic csv download) that have question 84.

```sql
SELECT  id
FROM    programs
WHERE   id IN (SELECT  DISTINCT program_id
               FROM    applications)
  AND   block_definitions::TEXT LIKE '%{"id": 84}%';
 id  
-----
 188
 190
(2 rows)
```

Both of them are in version 14

```sql
select * from versions_programs where programs_id in (188, 190);
 programs_id | versions_id 
-------------+-------------
         188 |          14
         190 |          14
(2 rows)
```

While in version 14, only the new version of the question (id 144) is present. (Versions of the same question cannot appear in the same version)

```sql
select * from versions_questions where versions_id = 14 and questions_id in (84, 144);
 questions_id | versions_id 
--------------+-------------
          144 |          14
(1 row)
```

**Comment by hmhsu** [comment]
To see what other programs have the same problem, I created this SQL statement to flatten questions in programs.

```sql
SELECT  vp.versions_id,
        p.id pid,
        CAST (
            jsonb_array_elements(
                jsonb_array_elements(p.block_definitions) -> 'questionDefinitions'
            ) -> 'id' AS bigint
        ) qid
FROM programs p
JOIN versions_programs vp
  ON p.id = vp.programs_id;
```

Here is what we got, version 38 is draft so we don't need to worry.
```sql
SELECT  DISTINCT qid
FROM    (SELECT vp.versions_id,
                p.id pid,
                CAST (
                    jsonb_array_elements(
                        jsonb_array_elements(p.block_definitions) -> 'questionDefinitions'
                    ) -> 'id' AS bigint
                 ) qid
    FROM programs p
    JOIN versions_programs vp
      ON p.id = vp.programs_id) pq
WHERE NOT EXISTS (SELECT 1
                  FROM  versions_questions vq
                  WHERE vq.versions_id = pq.versions_id
                    AND vq.questions_id = pq.qid)
  AND versions_id < 38;
 qid 
-----
 84
 92
(2 rows)
```

Question 84 is there, and there is also question 92.

**Comment by hmhsu** [comment]
Here is the full result

```sql
SELECT  *
FROM    (SELECT vp.versions_id,
                p.id pid,
                CAST (
                    jsonb_array_elements(
                        jsonb_array_elements(p.block_definitions) -> 'questionDefinitions'
                    ) -> 'id' AS bigint
                 ) qid
    FROM programs p
    JOIN versions_programs vp
      ON p.id = vp.programs_id) pq
WHERE NOT EXISTS (SELECT 1
                  FROM  versions_questions vq
                  WHERE vq.versions_id = pq.versions_id
                    AND vq.questions_id = pq.qid)
  AND versions_id < 38;
 versions_id | pid | qid 
-------------+-----+-----
          10 | 181 | 84
          10 | 181 | 92
          11 | 184 | 84
          11 | 184 | 92
          11 | 185 | 84
          11 | 185 | 92
          12 | 186 | 84
          12 | 186 | 92
          12 | 184 | 84
          12 | 184 | 92
          12 | 185 | 84
          12 | 185 | 92
          13 | 187 | 84
          13 | 187 | 92
          13 | 185 | 84
          13 | 185 | 92
          13 | 186 | 84
          13 | 186 | 92
          14 | 188 | 84
          14 | 188 | 92
          14 | 189 | 84
          14 | 189 | 92
          14 | 190 | 84
          14 | 190 | 92
(24 rows)
```

And the problem versions and programs
```sql
SELECT  DISTINCT versions_id, pid
FROM    (SELECT vp.versions_id,
                p.id pid,
                CAST (
                    jsonb_array_elements(
                        jsonb_array_elements(p.block_definitions) -> 'questionDefinitions'
                    ) -> 'id' AS bigint
                 ) qid
    FROM programs p
    JOIN versions_programs vp
      ON p.id = vp.programs_id) pq
WHERE NOT EXISTS (SELECT 1
                  FROM  versions_questions vq
                  WHERE vq.versions_id = pq.versions_id
                    AND vq.questions_id = pq.qid)
  AND versions_id < 38;
 versions_id | pid 
-------------+-----
          10 | 181
          11 | 184
          11 | 185
          12 | 184
          12 | 185
          12 | 186
          13 | 185
          13 | 186
          13 | 187
          14 | 188
          14 | 189
          14 | 190
(12 rows)
```

**Comment by hmhsu** [comment]
Question 84 and 92 are the ones that broke in #1290.

See debugging discussion starting from https://civiform.slack.com/archives/C02022VFNCF/p1622593264225300

The better fix here is to update those block definitions, let me see if I can do that.

**Comment by hmhsu** [comment]
```sql
update programs set block_definitions = jsonb_set(block_definitions, '{0,questionDefinitions,0,id}', jsonb '144', false) where id = 181;
```
appears to work. I am going to manually update all programs.

**Comment by hmhsu** [comment]
```sql
update programs set block_definitions = jsonb_set(block_definitions, '{0,questionDefinitions,0,id}', jsonb '144', false) where id = 184;
UPDATE 1
update programs set block_definitions = jsonb_set(block_definitions, '{0,questionDefinitions,0,id}', jsonb '144', false) where id = 185;
UPDATE 1
update programs set block_definitions = jsonb_set(block_definitions, '{0,questionDefinitions,0,id}', jsonb '144', false) where id = 186;
UPDATE 1
update programs set block_definitions = jsonb_set(block_definitions, '{0,questionDefinitions,0,id}', jsonb '144', false) where id = 187;
UPDATE 1
update programs set block_definitions = jsonb_set(block_definitions, '{0,questionDefinitions,0,id}', jsonb '144', false) where id = 188;
UPDATE 1
update programs set block_definitions = jsonb_set(block_definitions, '{0,questionDefinitions,0,id}', jsonb '144', false) where id = 189;
UPDATE 1
update programs set block_definitions = jsonb_set(block_definitions, '{0,questionDefinitions,0,id}', jsonb '144', false) where id = 190;
UPDATE 1

update programs set block_definitions = jsonb_set(block_definitions, '{3,questionDefinitions,0,id}', jsonb '162', false) where id = 181;
UPDATE 1
update programs set block_definitions = jsonb_set(block_definitions, '{3,questionDefinitions,0,id}', jsonb '162', false) where id = 184;
UPDATE 1
update programs set block_definitions = jsonb_set(block_definitions, '{3,questionDefinitions,0,id}', jsonb '162', false) where id = 186;
UPDATE 1
update programs set block_definitions = jsonb_set(block_definitions, '{3,questionDefinitions,0,id}', jsonb '162', false) where id = 187;
UPDATE 1
update programs set block_definitions = jsonb_set(block_definitions, '{3,questionDefinitions,0,id}', jsonb '162', false) where id = 189;
UPDATE 1
update programs set block_definitions = jsonb_set(block_definitions, '{3,questionDefinitions,0,id}', jsonb '162', false) where id = 190;
UPDATE 1

update programs set block_definitions = jsonb_set(block_definitions, '{6,questionDefinitions,0,id}', jsonb '162', false) where id = 185;
UPDATE 1
update programs set block_definitions = jsonb_set(block_definitions, '{6,questionDefinitions,0,id}', jsonb '162', false) where id = 188;
UPDATE 1
```

Now all the problem programs are fixed.
```sql
SELECT  *
FROM    (SELECT vp.versions_id,
                p.id pid,
                CAST (
                    jsonb_array_elements(
                        jsonb_array_elements(p.block_definitions) -> 'questionDefinitions'
                    ) -> 'id' AS bigint
                 ) qid
    FROM programs p
    JOIN versions_programs vp
      ON p.id = vp.programs_id) pq
WHERE NOT EXISTS (SELECT 1
                  FROM  versions_questions vq
                  WHERE vq.versions_id = pq.versions_id
                    AND vq.questions_id = pq.qid)
  AND versions_id < 38;
 versions_id | pid | qid 
-------------+-----+-----
(0 rows)
```

**Comment by hmhsu** [comment]
I think now we finally fixed everything on this problem (hopefully).

@elisekalstad would you help try again and let me know if you still see an error?

**Comment by hmhsu** [comment]
Due to discovery in this issue, we know that the database backups have corrupted data up to this point. So we cannot rollback to any backup before this date. Good news is if the fix is confirmed working, going forward we should have good backups.

**Comment by elisekalstad** [comment]
Looks good! I'm able to download the CSV without any errors. Thanks, Hung-Ming @hmhsu !
