### ISSUE TITLE
Error message when downloading applications

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1797]
**Describe the bug**
I'm working with the UDP team on a revised form. The form is currently hidden from public view (but accessible here: https://civiform.seattle.gov/programs/testing_genericprogram). Program Admins need to be able to download the CSV export in order to process the applications. Unfortunately, the program admins assigned to this test program received an error message: 7m9pdk154

**To Reproduce**
1. (check that user is on VPN)
2. Login as CiviForm Admin
3. Click on program
4. Click to download all versions (to export CSV with ALL applications)
5. See error

**Expected behavior**
Program Admins Thor and Jessica should be able to download a CSV with all applications and attachments

**Screenshots**
Attached

![Uploading CiviForm Download Error 01 07 22.png…]()

**Comment by elisekalstad** [comment]
![Uploading CiviForm Download Error 01 07 22.png…]()

**Comment by elisekalstad** [comment]
![CiviForm Download Error 01 07 22](https://user-images.githubusercontent.com/86082659/148834477-d207b66f-c37d-4539-9897-5f2605fe6686.png)

**Comment by bion** [comment]
Found stack trace in prod logs:
```
! @7m9pdk154 - Internal server error, for (GET) [/admin/programs/449/applications/all] ->
--
 
play.api.UnexpectedException: Unexpected exception[CompletionException: java.lang.RuntimeException: java.lang.RuntimeException: services.question.exceptions.QuestionNotFoundException: Question not found for ID: 665]
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:264)
at play.core.server.AkkaHttpServer$anonfun$2.applyOrElse(AkkaHttpServer.scala:430)
at play.core.server.AkkaHttpServer$anonfun$2.applyOrElse(AkkaHttpServer.scala:422)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:453)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.RuntimeException: services.question.exceptions.QuestionNotFoundException: Question not found for ID: 665
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:670)
at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
at java.base/java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:2104)
at java.base/java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:143)
at play.libs.streams.Accumulator$StrictAccumulator.lambda$map$0(Accumulator.java:388)
at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
at play.libs.streams.Accumulator$StrictAccumulator$1.apply(Accumulator.java:431)
at play.libs.streams.Accumulator$StrictAccumulator$1.apply(Accumulator.java:428)
at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
at play.api.libs.streams.StrictAccumulator.run(Accumulator.scala:199)
at play.core.server.AkkaHttpServer.$anonfun$runAction$4(AkkaHttpServer.scala:417)
at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: services.question.exceptions.QuestionNotFoundException: Question not found for ID: 665
at org.pac4j.play.java.SecureAction.call(SecureAction.java:79)
at play.core.j.JavaAction.$anonfun$apply$8(JavaAction.scala:175)
at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:661)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:430)
at play.core.j.HttpExecutionContext.$anonfun$execute$1(HttpExecutionContext.scala:64)
at play.api.libs.streams.Execution$trampoline$.execute(Execution.scala:70)
at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:59)
at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:392)
at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:302)
at scala.concurrent.impl.Promise$DefaultPromise.dispatchOrAddCallbacks(Promise.scala:276)
at scala.concurrent.impl.Promise$DefaultPromise.map(Promise.scala:146)
at scala.concurrent.Future$.apply(Future.scala:661)
at play.core.j.JavaAction.apply(JavaAction.scala:176)
at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:168)
at scala.util.Try$.apply(Try.scala:210)
at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$3(Accumulator.scala:168)
at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
at scala.Function1.$anonfun$andThen$1(Function1.scala:85)
at play.api.libs.streams.StrictAccumulator.$anonfun$asJava$2(Accumulator.scala:204)
Caused by: java.lang.RuntimeException: services.question.exceptions.QuestionNotFoundException: Question not found for ID: 665
at services.program.ProgramServiceImpl.syncProgramQuestionDefinition(ProgramServiceImpl.java:679)
at services.program.ProgramServiceImpl.syncBlockDefinitionQuestions(ProgramServiceImpl.java:663)
at services.program.ProgramServiceImpl.syncProgramDefinitionQuestions(ProgramServiceImpl.java:646)
at services.program.ProgramServiceImpl.syncProgramDefinitionQuestions(ProgramServiceImpl.java:635)
at services.program.ProgramServiceImpl.syncProgramAssociations(ProgramServiceImpl.java:100)
at services.program.ProgramServiceImpl.lambda$getAllProgramDefinitionVersions$10(ProgramServiceImpl.java:577)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
at services.program.ProgramServiceImpl.getAllProgramDefinitionVersions(ProgramServiceImpl.java:578)
at services.export.ExporterService.getProgramAllVersionsCsv(ExporterService.java:78)
at controllers.admin.AdminApplicationController.downloadAll(AdminApplicationController.java:71)
at router.Routes$anonfun$routes$1.$anonfun$applyOrElse$141(Routes.scala:2408)
at play.core.routing.HandlerInvokerFactory$anon$8.resultCall(HandlerInvoker.scala:150)
at play.core.routing.HandlerInvokerFactory$anon$8.resultCall(HandlerInvoker.scala:149)
at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$anon$3$anon$4$anon$5.invocation(HandlerInvoker.scala:115)
Caused by: services.question.exceptions.QuestionNotFoundException: Question not found for ID: 665
at services.question.ReadOnlyVersionedQuestionServiceImpl.getQuestionDefinition(ReadOnlyVersionedQuestionServiceImpl.java:64)
at services.program.ProgramServiceImpl.syncProgramQuestionDefinition(ProgramServiceImpl.java:676)
at services.program.ProgramServiceImpl.syncBlockDefinitionQuestions(ProgramServiceImpl.java:663)
at services.program.ProgramServiceImpl.syncProgramDefinitionQuestions(ProgramServiceImpl.java:646)
at services.program.ProgramServiceImpl.syncProgramDefinitionQuestions(ProgramServiceImpl.java:635)
at services.program.ProgramServiceImpl.syncProgramAssociations(ProgramServiceImpl.java:100)
at services.program.ProgramServiceImpl.lambda$getAllProgramDefinitionVersions$10(ProgramServiceImpl.java:577)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
at services.program.ProgramServiceImpl.getAllProgramDefinitionVersions(ProgramServiceImpl.java:578)
at services.export.ExporterService.getProgramAllVersionsCsv(ExporterService.java:78)
at controllers.admin.AdminApplicationController.downloadAll(AdminApplicationController.java:71)
at router.Routes$anonfun$routes$1.$anonfun$applyOrElse$141(Routes.scala:2408)
at play.core.routing.HandlerInvokerFactory$anon$8.resultCall(HandlerInvoker.scala:150)
at play.core.routing.HandlerInvokerFactory$anon$8.resultCall(HandlerInvoker.scala:149)
```

**Comment by bion** [comment]
Attempting to download all applications for program 449, at some point looking for question 655 which is not in the database.

**Comment by bion** [comment]
Program 449 is "TESTING_GenericProgram". Other version IDs are:

 364
 370
 374
 376
 383
 391
 398
 404
 410
 421
 423
 426
 427
 428
 429
 430
 431
 434
 435
 436
 437
 438
 440
 441
 442
 443
 444
 445
 446
 447
 448
 449
 451

**Comment by bion** [comment]
Question 655 *does* exist in the database:
```
 id  |                       name                        |                    description                    | question_type | legacy_question_text | legacy_question_help_text | validation_predicates | legacy_question_options | enumerator_id | question_options |                                          question_text                                          |                               question_help_text                                | enumerator_entity_type | question_tags 
-----+---------------------------------------------------+---------------------------------------------------+---------------+----------------------+---------------------------+-----------------------+-------------------------+---------------+------------------+-------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+------------------------+---------------
 655 | Household Member Income Upload – Adoption Support | Household Member Income Upload – Adoption Support | FILEUPLOAD    |                      |                           | "{}"                  |                         |           407 |                  | {"isRequired": true, "translations": {"en_US": "Please upload $this’s adoption award letter."}} | {"isRequired": true, "translations": {"en_US": "Choose file for $this below."}} |                        | 
 ```

**Comment by bion** [comment]
Mitigated for now by manually adding associations in prod:
```
insert into versions_questions(versions_id, questions_id) values (145, 666);
insert into versions_questions(versions_id, questions_id) values (145, 665);
```
