### ISSUE TITLE
Date Parsing Exception When Saving Application

### ISSUE THREAD

**Issue by gwendolyngoetz** [seattle-uat/civiform#2125]
Splitting this off from issue #2014 

--

From @elisekalstad 

3/16 ORCA Opportunity program: "Oops…..and error occurred. This exception has been logged with id 7n33879ep"

**Comment by gwendolyngoetz** [comment]
There is a date parsing issue occurring. We need to gracefully handle it and make sure user is given a validation error. 

Shane thinks it could be caused by different browser locales settings.




```
play.api.UnexpectedException: Unexpected exception[CompletionException: java.lang.RuntimeException: java.time.format.DateTimeParseException: Text '01/01/1942' could not be parsed at index 0]
--
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:264)
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: java.time.format.DateTimeParseException: Text '01/01/1942' could not be parsed at index 0
at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:970)
Caused by: java.lang.RuntimeException: java.time.format.DateTimeParseException: Text '01/01/1942' could not be parsed at index 0
at controllers.applicant.ApplicantProgramBlocksController.handleUpdateExceptions(ApplicantProgramBlocksController.java:459)
at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:986)
Caused by: java.time.format.DateTimeParseException: Text '01/01/1942' could not be parsed at index 0
[[31merror[0m] p.a.h.DefaultHttpErrorHandler -

```

**Comment by clouser2** [comment]
@gwendolyngoetz, I have a fix for this as part of https://github.com/seattle-uat/civiform/issues/1944. Mind if I grab this from you?

When using `input[type="date"]`, browsers would prevent specifying an input value of this type. Server-side, we expect `01-01-1942`. In this case, the applicant may have been using a browser without full support for `input[type="date"]`. In an upcoming PR, I'll display an error message indicating the expected format.

**Comment by gwendolyngoetz** [comment]
@clouser2 Go for it
